version: '3'

services:
  fabrikamfiber.web:
    ports:
      - "80"
    depends_on:
      - db
    environment:
      DB_SA_PASSWORD: "Password1"
      DB_SERVICE_HOST: "db"
      DB_SERVICE_PORT: 1433
  db:
    image: microsoft/mssql-server-windows-developer:1709
    environment:
      SA_PASSWORD: "Password1"
      ACCEPT_EULA: "Y"
    ports:
      - "1433"
    healthcheck:
      test: [ "CMD", "sqlcmd", "-U", "sa", "-P", "Password1", "-Q", "select 1" ]
      interval: 1s
      retries: 20
networks:
  default:
    external:
      name: nat
